### ISSUE TITLE
[Design] закруглить карты, добавить каймы на карты

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/Imaginarium#96]

**Comment by asoman** [comment]
Шейдеры...  либо вручную резать. При этом второй вариант так то лучше. Ибо у разных картинок нужно оставить разные куски...

**Comment by asoman** [comment]
Кайма есть. Одна карта (66) вырезана по шаблону для тестов.

Морально готовлюсь к шейдерам
